language: python
python:
  #- "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# command to install dependencies
install:
  #will work on py26, but not now
  #- pip install unittest2   #try to backport unittest.skip
  - pip install --upgrade .
# command to run tests
script:
  #- mkdir -p tests/test_data/images/emptyFolder
  - python setup.py test
