language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# command to install dependencies
install: "pip install --upgrade ."
# command to run tests
script:
  #- mkdir -p tests/test_data/images/emptyFolder
  - python setup.py test